const COL_WIDTH = 130;
const WIDTH_4_PERCENT = 50;

export const type1 = [
  {
    columnId: "product_code",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "product_description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },
  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type2 = [
  {
    columnId: "product_code",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "product_description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },

  {
    columnId: "jan",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "feb",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "mar",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "apr",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "mei",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "jun",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "jul",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "agu",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "sep",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "okt",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "nov",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "des",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  {
    columnId: "jan_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "feb_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "mar_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "apr_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "mei_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "jun_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "jul_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "agu_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "sep_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "okt_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "nov_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  {
    columnId: "des_p",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type3 = [
  {
    columnId: "product_code",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "product_description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },
  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", nonEditabled: true },
];

export const type4 = [
  {
    columnId: "product_code",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "product_description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },

  {
    columnId: "jan_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jan", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "feb_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "feb", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "mar_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mar", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "apr_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "apr", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "mei_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mei", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "jun_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jun", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "jul_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jul", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "agu_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "agu", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "sep_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "sep", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "okt_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "okt", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "nov_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "nov", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "des_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "des", width: WIDTH_4_PERCENT, type: "percent" },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  {
    columnId: "jan_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jan_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "feb_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "feb_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "mar_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mar_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "apr_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "apr_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "mei_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mei_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "jun_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jun_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "jul_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jul_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "agu_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "agu_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "sep_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "sep_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "okt_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "okt_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "nov_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "nov_p", width: WIDTH_4_PERCENT, type: "percent" },
  {
    columnId: "des_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "des_p", width: WIDTH_4_PERCENT, type: "percent" },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type5 = [
  {
    columnId: "code_account",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },

  {
    columnId: "jan_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jan", width: COL_WIDTH, type: "percent" },
  {
    columnId: "feb_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "feb", width: COL_WIDTH, type: "percent" },
  {
    columnId: "mar_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mar", width: COL_WIDTH, type: "percent" },
  {
    columnId: "apr_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "apr", width: COL_WIDTH, type: "percent" },
  {
    columnId: "mei_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mei", width: COL_WIDTH, type: "percent" },
  {
    columnId: "jun_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jun", width: COL_WIDTH, type: "percent" },
  {
    columnId: "jul_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jul", width: COL_WIDTH, type: "percent" },
  {
    columnId: "agu_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "agu", width: COL_WIDTH, type: "percent" },
  {
    columnId: "sep_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "sep", width: COL_WIDTH, type: "percent" },
  { columnId: "okt_sd", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  {
    columnId: "nov_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "nov", width: COL_WIDTH, type: "percent" },
  {
    columnId: "des_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "des", width: COL_WIDTH, type: "percent" },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  {
    columnId: "jan_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jan_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "feb_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "feb_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "mar_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mar_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "apr_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "apr_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "mei_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "mei_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "jun_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jun_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "jul_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "jul_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "agu_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "agu_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "sep_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "sep_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "okt_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "okt_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "nov_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "nov_p", width: COL_WIDTH, type: "percent" },
  {
    columnId: "des_p_sd",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
  { columnId: "des_p", width: COL_WIDTH, type: "percent" },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type6 = [
  {
    columnId: "code_account",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },

  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type7 = [
  {
    columnId: "description",
    width: 200,
    type: "text",
    nonEditabled: true,
  },

  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: true,
    nonEditabled: true,
  },
];

export const type8 = [
  {
    columnId: "product_code",
    width: 80,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "product_description",
    width: 400,
    type: "text",
    nonEditabled: true,
  },
  { columnId: "jan", width: COL_WIDTH, type: "number", format: false },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: false },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: false },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: false },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: false },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: false },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: false },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: false },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: false },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: false },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: false },
  { columnId: "des", width: COL_WIDTH, type: "number", format: false },

  {
    columnId: "total_1",
    width: COL_WIDTH,
    type: "number",
    format: false,
    nonEditabled: true,
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: false },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: false },

  {
    columnId: "total_2",
    width: COL_WIDTH,
    type: "number",
    format: false,
    nonEditabled: true,
  },
];

export const getColumns = {
  "Stok Awal": type8,
  "Asumsi unit beli": type8,
  "Harga beli per unit": type3,
  "Stok akhir": type2,
  "Asumsi unit jual": type8,
  "Harga jual per unit": type3,
  "Volume / Unit": type1,
  Tarif: type3,
  "Asumsi trip": type3,
  "All data": type7,
  Penjualan: type2,
  "Potongan penjualan": type4,
  "Pendapatan Operasional Lainnya": type6,
  "HPP Variable": type5,
  "HPP Lainnya": type6,
};
