export const allItemSummarySubMenu = [
  [],
  [
    "Revenue & COGS HK",
    "Revenue & COGS KIU",
    "Revenue & COGS BTS",
    "Revenue & COGS KIA",
    "Revenue & COGS BJU",
    "Revenue & COGS BLT",
    "Revenue & COGS BLU",
    "Revenue & COGS BK",
    "Revenue & COGS BSU",
    "Revenue & COGS BSB",
    "Revenue & COGS KIK",
    "Revenue & COGS IKP",
    "Revenue & COGS BAND",
    "Summary Revenue & COGS",
  ],
  [
    "Iklan & Advertensi",
    "Pemasaran Lainnya",
    "Sewa",
    "Pemeliharaan",
    "Perlengkapan Kantor",
    "Pengiriman Dokumen",
    "FC, Cetakan & Jilid",
    "Listrik, Air & Telepon",
    "Surat Kabar",
    "Pantri",
    "Asuransi",
    "Keamanan & Kebersihan",
    "Internet",
    "Tender",
    "Kontraktual, Rapat, Clearance",
    "BBM, Tol, Parkir",
    "Transportasi",
    "Perjalanan Dinas",
    "Pajak Kendaraan",
    "Pajak",
    "Pajak Parkir & Resto",
    "Izin & Konsultan",
    "Administrasi Lainnya",
    "Risiko",
    "Summary Opex",
  ],
  ["Existing Aset", "New Aset", "Summary Capex", "Existing Penyusutan", "Saldo Awal Akumulasi", "New Aset", "New Aset Penyusutan", "New Aset Akumulasi", "Total Aset", "Total Penyusutan", "Total Akumulasi Penyusutan"],
  ["Rate", "Gaji", "Tunjangan", "Lembur", "THR & Bonus", "BPJS", "Kesejahteraan Karyawan", "PPH 21", "DPLK", "Pendidikan Dan Pelatihan", "Summary MPP"],
  ["Pendapatan Non Operasional", "Biaya Non Operasional", "Direct All", "Asumsi"],
  [],
  ["Kode perusahaan", "Kode produk", "Kode lokasi", "Kode departemen", "Kode akun", "Kode projek", "Kode ICP"],
  ["Profile", "Logout"],
];

export const disabledItemSummaryMenu = [
  [],
  [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
  [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
  [true, true, false, true, true, true, true, true, true, true, true],
  [true, true, true, true, true, true, true, true, true, true, false],
  [false, false, true, true],
  [],
  [false, false, false, false, false, false, false],
  [false, false],
];

export const endPointGetCoa = "";
