export const allItemSummarySubMenu = [
  [],
  [
    "Revenue & COGS HK",
    "Revenue & COGS KIU",
    "Revenue & COGS BTS",
    "Revenue & COGS KIA",
    "Revenue & COGS BJU",
    "Revenue & COGS BLT",
    "Revenue & COGS BLU",
    "Revenue & COGS BK",
    "Revenue & COGS BSU",
    "Revenue & COGS BSB",
    "Revenue & COGS KIK",
    "Revenue & COGS IKP",
    "Revenue & COGS BAND",
    "Summary Revenue & COGS",
  ],
  [
    "Input By Iklan & Advertensi",
    "Input By Pemasaran Lainnya",
    "Input By Sewa",
    "Input By Pemeliharaan",
    "Input By Perlengkapan Kantor",
    "Input By Pengiriman Dokumen",
    "Input By FC, Cetakan & Jilid",
    "Input By Listrik, Air & Telepon",
    "Input By Surat Kabar",
    "Input By Pantri",
    "Input By Asuransi",
    "Input By Keamanan & Kebersihan",
    "Input By Internet",
    "Input By Tender",
    "Input By Kontraktual, Rapat, Clearance",
    "Input By BBM, Tol, Parkir",
    "Input By Transportasi",
    "Input By Perjalanan Dinas",
    "Input By Pajak Kendaraan",
    "Input By Pajak",
    "Input By Pajak Parkir & Resto",
    "Input By Izin & Konsultan",
    "Input By Administrasi Lainnya",
    "Input By Risiko",
    "Input By Operasional Lainnya",
    "Input By Opex Direct",
    "Summary By Iklan & Advertensi",
    "Summary By Pemasaran Lainnya",
    "Summary By Sewa",
    "Summary By Pemeliharaan",
    "Summary By Perlengkapan Kantor",
    "Summary By Pengiriman Dokumen",
    "Summary By FC, Cetakan & Jilid",
    "Summary By Listrik, Air & Telepon",
    "Summary By Surat Kabar",
    "Summary By Pantri",
    "Summary By Asuransi",
    "Summary By Keamanan & Kebersihan",
    "Summary By Internet",
    "Summary By Tender",
    "Summary By Kontraktual, Rapat, Clearance",
    "Summary By BBM, Tol, Parkir",
    "Summary By Transportasi",
    "Summary By Perjalanan Dinas",
    "Summary By Pajak Kendaraan",
    "Summary By Pajak",
    "Summary By Pajak Parkir & Resto",
    "Summary By Izin & Konsultan",
    "Summary By Administrasi Lainnya",
    "Summary By Risiko",
    "Summary By Operasional Lainnya",
    "Summary Budget Opex",
  ],
  [
    "Existing Aset",
    "New Aset",
    "Summary Capex",
    "Existing Penyusutan",
    "Saldo Awal Akumulasi",
    "New Aset",
    "New Aset Penyusutan",
    "New Aset Akumulasi",
    "Total Aset",
    "Total Penyusutan",
    "Total Akumulasi Penyusutan",
  ],
  [
    "Rate",
    "Gaji",
    "Tunjangan",
    "Lembur",
    "THR & Bonus",
    "BPJS",
    "Kesejahteraan Karyawan",
    "PPH 21",
    "DPLK",
    "Pendidikan Dan Pelatihan",
    "Summary MPP",
  ],
  [
    "Pendapatan Non Operasional",
    "Biaya Non Operasional",
    "Direct All",
    "Asumsi",
  ],
  [],
  [
    "Kode perusahaan",
    "Kode produk",
    "Kode lokasi",
    "Kode departemen",
    "Kode akun",
    "Kode projek",
    "Kode ICP",
  ],
  ["Profile", "Logout"],
];

export const disabledItemSummaryMenu = [
  [],
  [
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    true,
    false,
  ],
  [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
  ],
  [true, true, false, true, true, true, true, true, true, true, true],
  [true, true, true, true, true, true, true, true, true, true, false],
  [false, false, true, true],
  [],
  [false, false, false, false, false, false, false],
  [false, false],
];

export const endPointGetCoa = "";
