export const allItemSummarySubMenu = [
  // 1 Dashboard
  [],
  // 2 Revenue & COGS
  [
    "Revenue & COGS HK",
    "Revenue & COGS KIU",
    "Revenue & COGS BTS",
    "Revenue & COGS KIA",
    "Revenue & COGS BJU",
    "Revenue & COGS BLT",
    "Revenue & COGS BLU",
    "Revenue & COGS BK",
    "Revenue & COGS BSU",
    "Revenue & COGS BSB",
    "Revenue & COGS KIK",
    "Revenue & COGS IKP",
    "Revenue & COGS BAND",
    "Input Direct Revenue & COGS",
    "Summary Revenue & COGS",
  ],
  // 3 Opex
  [
    "Input By Iklan & Advertensi",
    "Input By Pemasaran Lainnya",
    "Input By Sewa",
    "Input By Pemeliharaan",
    "Input By Perlengkapan Kantor",
    "Input By Pengiriman Dokumen",
    "Input By FC, Cetakan & Jilid",
    "Input By Listrik, Air & Telepon",
    "Input By Surat Kabar",
    "Input By Pantri",
    "Input By Asuransi",
    "Input By Keamanan & Kebersihan",
    "Input By Internet",
    "Input By Tender",
    "Input By Kontraktual, Rapat, Clearance",
    "Input By BBM, Tol, Parkir",
    "Input By Transportasi",
    "Input By Perjalanan Dinas",
    "Input By Pajak Kendaraan",
    "Input By Pajak",
    "Input By Pajak Parkir & Resto",
    "Input By Izin & Konsultan",
    "Input By Administrasi Lainnya",
    "Input By Risiko",
    "Input By Operasional Lainnya",
    "Input By Opex Direct",
    "Summary By Iklan & Advertensi",
    "Summary By Pemasaran Lainnya",
    "Summary By Sewa",
    "Summary By Pemeliharaan",
    "Summary By Perlengkapan Kantor",
    "Summary By Pengiriman Dokumen",
    "Summary By FC, Cetakan & Jilid",
    "Summary By Listrik, Air & Telepon",
    "Summary By Surat Kabar",
    "Summary By Pantri",
    "Summary By Asuransi",
    "Summary By Keamanan & Kebersihan",
    "Summary By Internet",
    "Summary By Tender",
    "Summary By Kontraktual, Rapat, Clearance",
    "Summary By BBM, Tol, Parkir",
    "Summary By Transportasi",
    "Summary By Perjalanan Dinas",
    "Summary By Pajak Kendaraan",
    "Summary By Pajak",
    "Summary By Pajak Parkir & Resto",
    "Summary By Izin & Konsultan",
    "Summary By Administrasi Lainnya",
    "Summary By Risiko",
    "Summary By Operasional Lainnya",
    "Summary Budget Opex",
  ],
  // 4 Capex
  [
    "Input Existing Aset",
    "Input New Aset",
    "Input Direct Capex",
    "Summary Capex",
    "Summary Existing Aset",
    "Summary Existing Penyusutan",
    "Summary Saldo Awal Akumulasi",
    "Summary New Aset",
    "Summary New Aset Penyusutan",
    "Summary New Aset Akumulasi",
    "Summary Total Aset",
    "Summary Total Penyusutan",
    "Summary Total Akumulasi Penyusutan",
  ],
  // 5 MPP
  [
    "MPP General Asumption",
    "Input Rate Assumption",
    "Input Rate Salary",
    "Input Headcount Salary",
    "Input Headcount Assumption",
    "Input Days",
    "Input Jam Lembur",
    "Input by lembur",
    "Input Biaya Pengobatan",
    "Input Biaya PPh 21",
    "Input Biaya BPJS TK",
    "Input Biaya BPJS Kesehatan",
    "Input Biaya Pendidikan & Latihan",
    "Input Biaya Rekrutment & Assessment",
    "Input Biaya Uniform & Safety",
    "Input Biaya DPLK",
    "Input Biaya MPP Lainnya",
    "Input MPP Direct",
    "Summary Gaji",
    "Summary By THR",
    "Summary By Lembur",
    "Summary By Makan dan Minum",
    "Summary By Pengobatan",
    "Summary By PPh Pasal 21",
    "Summary By BPJS TK",
    "Summary By BPJS Kesehatan",
    "Summary By Transportasi",
    "Summary By Komunikasi",
    "Summary By Pendidikan & Pelatihan",
    "Summary By Rekrutment & Assessment",
    "Summary By Uniform & Safety",
    "Summary By DPLK",
    "Summary By MPP Lainnya",
    "Summary MPP",
  ],
  // 6 Others
  [
    "Input Direct Pendapatan Non Operasional",
    "Input Direct Biaya Non Operasional",
    "Input Direct All",
    "Summary Biaya Non Operasional",
    "Summary Pendapatan Non Operasional",
  ],
  // 7 Report
  [],
  // 8 Master COA
  [
    "Kode perusahaan",
    "Kode produk",
    "Kode lokasi",
    "Kode departemen",
    "Kode akun",
    "Kode projek",
    "Kode ICP",
  ],
  // 9 Akun
  ["Profile", "Logout"],
];

export const disabledItemSummaryMenu = [
  // 1 Dashboard
  [],
  // 2 Revenue & COGS
  [
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
  ],
  // 3 Opex
  [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
  ],
  // 4 Capex
  [
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
  ],
  // 5 MPP
  [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
  ],
  // 6 Others
  [false, false, true, false, false],
  // 7 Report
  [],
  // 8 Master COA
  [false, false, false, false, false, false, false],
  // 9 Akun
  [false, false],
];

export const endPointGetCoa = "";
