export const routingRevenue = {
  hk: "Revenue & COGS HK",
  kiu: "Revenue & COGS KIU",
  gmm: "Revenue & COGS GMM",
  kia: "Revenue & COGS KIA",
  bju: "Revenue & COGS BJU",
  blt: "Revenue & COGS BLT",
  blu: "Revenue & COGS BLU",
  bk: "Revenue & COGS BK",
  bsu: "Revenue & COGS BSU",
  bsb: "Revenue & COGS BSB",
  kik: "Revenue & COGS KIK",
  ikp: "Revenue & COGS IKP",
  band: "Revenue & COGS BAND",
  "Input Direct Revenue & COGS": "direct",
  "Summary Revenue & COGS": "direct",
};
export const routingOpex = {
  "Input By Iklan & Advertensi": "iklan-advertensi",
  "Input By Pemasaran Lainnya": "pemasaran-lainnya",
  "Input By Sewa": "sewa",
  "Input By Pemeliharaan": "pemeliharaan",
  "Input By Perlengkapan Kantor": "perlengkapan-kantor",
  "Input By Pengiriman Dokumen": "pengiriman-dokumen",
  "Input By FC,Cetakan & Jilid": "fc-cetak-jilid",
  "Input By Listrik,Air & Telefon": "listrik-air-telefon",
  "Input By Surat Kabar": "surat-kabar",
  "Input By Pantri": "pantri",
  "Input By Asuransi": "asuransi",
  "Input By Keamanan & Kebersihan": "keamanan-kebersihan",
  "Input By Internet": "internet",
  "Input By Tender": "tender",
  "Input By Kontraktual, Rapat, Clearance": "kontraktual-rapat-clearance",
  "Input By BBM, Tol, Parkir": "bbm-tol-parkir",
  "Input By Transportasi": "transportasi",
  "Input By Perjalanan Dinas": "perjalanan-dinas",
  "Input By Pajak Kendaraan": "pajak-kendaraan",
  "Input By Pajak": "pajak",
  "Input By Pajak Parkir & Resto": "pajak-parkir-resto",
  "Input By Izin & Konsultan": "izin-konsultan",
  "Input By Administrasi Lainnya": "administrasi-lainnya",
  "Input By Opex Direct": "opex",
  "Summary By Iklan & Advertensi": "iklan-advertensi",
  "Summary By Pemasaran Lainnya": "pemasaran-lainnya",
  "Summary By Sewa": "sewa",
  "Summary By Pemeliharaan": "pemeliharaan",
  "Summary By Perlengkapan Kantor": "perlengkapan-kantor",
  "Summary By Pengiriman Dokumen": "pengiriman-dokumen",
  "Summary By FC,Cetakan & Jilid": "fc-cetak-jilid",
  "Summary By Listrik,Air & Telefon": "listrik-air-telefon",
  "Summary By Surat Kabar": "surat-kabar",
  "Summary By Pantri": "pantri",
  "Summary By Asuransi": "asuransi",
  "Summary By Keamanan & Kebersihan": "keamanan-kebersihan",
  "Summary By Internet": "internet",
  "Summary By Tender": "tender",
  "Summary By Kontraktual, Rapat, Clearance": "kontraktual-rapat-clearance",
  "Summary By BBM, Tol, Parkir": "bbm-tol-parkir",
  "Summary By Transportasi": "transportasi",
  "Summary By Perjalanan Dinas": "perjalanan-dinas",
  "Summary By Pajak Kendaraan": "pajak-kendaraan",
  "Summary By Pajak": "pajak",
  "Summary By Pajak Parkir & Resto": "pajak-parkir-resto",
  "Summary By Izin & Konsultan": "izin-konsultan",
  "Summary By Administrasi Lainnya": "administrasi-lainnya",
  "Summary Budget Opex": "opex",
};
export const routingCapex = {
  "Input Load Saldo Awal": "load-saldo-awal",
  "Input New Aset": "new-aset",
  "Input Direct Capex": "direct-capex",
  "Summary Existing Aset": "existing-aset",
  "Summary Penyusutan Existing Aset": "penyusutan-existing-aset",
  "Summary Saldo Awal Akumulasi Penyusutan": "saldo-awal-akumulasi-penyusutan",
  "Summary New Aset": "new-aset",
  "Summary Penyusutan New Aset": "penyusutan-new-aset",
  "Summary Akumulasi Penyusutan New Aset": "akumulasi-penyusutan-new-aset",
  "Summary Disposal Aset": "disposal-aset",
  "Summary Nilai Jual Aset": "nilai-jual-aset",
  "Summary Penyusutan Disposal Aset": "penyusutan-disposal-aset",
  "Summary Akumulasi Penyusutan Disposal Aset": "akumulasi-penyusutan-disposal-aset",
  "Summary Total Aset": "total-aset",
  "Summary Total Penyusutan": "total-penyusutan",
  "Summary Total Akumulasi Penyusutan": "total-akumulasi-penyusutan",

  "Summary Capex": "capex",
};
export const routingMpp = {
  "Input MPP General Asumption": "general-asumption",
  "Input Rate Assumption": "rate-asumption",
  "Input Rate Salary": "rate-salary",
  "Input Headcount Salary": "headcount-salary",
  "Input Headcount Assumption": "headcount-asumption",
  "Input Days": "days",
  "Input Jam Lembur": "jam-lembur",
  "Input Biaya Pengobatan": "biaya-pengobatan",
  "Input Biaya PPh 21": "biaya-pph21",
  "Input Biaya BPJS Kesehatan": "bpjs-kesehatan",
  "Input Biaya Pendidikan & Latihan": "biaya-pendidikan-latihan",
  "Input Biaya Rekrutment & Assessment": "rekrutment-assessment",
  "Input Biaya Uniform & Safety": "uniform-safety",
  "Input Biaya MPP Lainnya": "lainnya",
  "Input MPP Direct": "mpp",

  "Summary MPP": "mpp",
};
export const routingOthers = {
  "Input Direct Pendapatan Non Operasional": "pendapatan-non-operasional",
  "Input Direct Biaya Non Operasional": "biaya-non-operasional",
  "Input Direct All": "direct-all",
  "Summary Direct All": "direct-all",
  "Summary Biaya Non Operasional": "biaya-non-operasional",
  "Summary Pendapatan Non Operasional": "pendapatan-non-operasional",
};
export const routingReport = {
  "Laba Rugi": "laba-rugi",
  "Laba Rugi Testing": "laba-rugi-testing",
};
export const routingMasterCoa = {
  "Kode perusahaan": "perusahaan",
  "Kode produk": "produk",
  "Kode lokasi": "lokasi",
  "Kode departemen": "departement",
  "Kode akun": "akun",
  "Kode projek": "project",
  "Kode ICP": "icp",
};

export const allRouting = {
  "revenue-cogs": routingRevenue,
  opex: routingOpex,
  capex: routingCapex,
  mpp: routingMpp,
  others: routingOthers,
  report: routingReport,
  coa: routingMasterCoa,
};
