export const routingRevenue = {
  hk: "Revenue & COGS HK",
  kiu: "Revenue & COGS KIU",
  gmm: "Revenue & COGS GMM",
  kia: "Revenue & COGS KIA",
  bju: "Revenue & COGS BJU",
  blt: "Revenue & COGS BLT",
  blu: "Revenue & COGS BLU",
  bk: "Revenue & COGS BK",
  bsu: "Revenue & COGS BSU",
  bsb: "Revenue & COGS BSB",
  kik: "Revenue & COGS KIK",
  ikp: "Revenue & COGS IKP",
  band: "Revenue & COGS BAND",
};

export const routingOpex = {
  "Input By Iklan & Advertensi": "iklan-advertensi",
  "Input By Pemasaran Lainnya": "pemasaran-lainnya",
  "Input By Sewa": "sewa",
  "Input By Pemeliharaan": "pemeliharaan",
  "Input By Perlengkapan Kantor": "perlengkapan-kantor",
  "Input By Pengiriman Dokumen": "pengiriman-dokumen",
  "Input By FC,Cetakan & Jilid": "fc-cetak-jilid",
  "Input By Listrik,Air & Telefon": "listrik-air-telefon",
  "Input By Surat Kabar": "surat-kabar",
  "Input By Pantri": "pantri",
  "Input By Asuransi": "asuransi",
  "Input By Keamanan & Kebersihan": "keamanan-kebersihan",
  "Input By Internet": "internet",
  "Input By Tender": "tender",
  "Input By Kontraktual, Rapat, Clearance": "kontraktual-rapat-clearance",
  "Input By BBM, Tol, Parkir": "bbm-tol-parkir",
  "Input By Transportasi": "transportasi",
  "Input By Perjalanan Dinas": "perjalanan-dinas",
  "Input By Pajak Kendaraan": "pajak-kendaraan",
  "Input By Pajak": "pajak",
  "Input By Pajak Parkir & Resto": "pajak-parkir-resto",
  "Input By Izin & Konsultan": "izin-konsultan",
  "Input By Administrasi Lainnya": "administrasi-lainnya",
  "Input By Opex Direct": "opex",
  "Summary By Iklan & Advertensi": "iklan-advertensi",
  "Summary By Pemasaran Lainnya": "pemasaran-lainnya",
  "Summary By Sewa": "sewa",
  "Summary By Pemeliharaan": "pemeliharaan",
  "Summary By Perlengkapan Kantor": "perlengkapan-kantor",
  "Summary By Pengiriman Dokumen": "pengiriman-dokumen",
  "Summary By FC,Cetakan & Jilid": "fc-cetak-jilid",
  "Summary By Listrik,Air & Telefon": "listrik-air-telefon",
  "Summary By Surat Kabar": "surat-kabar",
  "Summary By Pantri": "pantri",
  "Summary By Asuransi": "asuransi",
  "Summary By Keamanan & Kebersihan": "keamanan-kebersihan",
  "Summary By Internet": "internet",
  "Summary By Tender": "tender",
  "Summary By Kontraktual, Rapat, Clearance": "kontraktual-rapat-clearance",
  "Summary By BBM, Tol, Parkir": "bbm-tol-parkir",
  "Summary By Transportasi": "transportasi",
  "Summary By Perjalanan Dinas": "perjalanan-dinas",
  "Summary By Pajak Kendaraan": "pajak-kendaraan",
  "Summary By Pajak": "pajak",
  "Summary By Pajak Parkir & Resto": "pajak-parkir-resto",
  "Summary By Izin & Konsultan": "izin-konsultan",
  "Summary By Administrasi Lainnya": "administrasi-lainnya",
  "Summary Budget Opex": "opex",
};
export const routingCapex = {
  "Input New Aset": "new-aset",
};
export const routingOthers = {
  "Input Direct Pendapatan Non Operasional": "Input Direct Pendapatan Non Operasional",
  "Input Direct Biaya Non Operasional": "Input Direct Biaya Non Operasional",
  "Input Direct All": "direct-all",
  "Summary Direct All": "direct-all",
  "Summary Biaya Non Operasional": "Summary Biaya Non Operasional",
  "Summary Pendapatan Non Operasional": "Summary Pendapatan Non Operasional",
};
export const routingReport = {
  "Laba Rugi": "laba-rugi",
  "Laba Rugi Testing": "laba-rugi-testing",
};
export const routingMasterCoa = {
  "Kode perusahaan": "perusahaan",
  "Kode produk": "produk",
  "Kode lokasi": "lokasi",
  "Kode departemen": "departement",
  "Kode akun": "akun",
  "Kode projek": "project",
  "Kode ICP": "icp",
};

export const allRouting = {
  "revenue-cogs": routingRevenue,
  opex: routingOpex,
  capex: routingCapex,
  others: routingOthers,
  report: routingReport,
  coa: routingMasterCoa,
};
