export const constantDataTable = {
  "Kode perusahaan": [
    {
      key: "0",
      kode_company: "0022",
      kode_parent: "0044",
      description: "Edward King 0",
    },
    {
      key: "1",
      kode_company: "0022",
      kode_parent: "0044",
      description: "Edward King 0",
    },
    {
      key: "2",
      kode_company: "0022",
      kode_parent: "0044",
      description: "Edward King 0",
    },
  ],
  "Kode produk": [
    {
      key: "0",
      kode_produk: "Edward King 0",
      kode_parent: "32",
      description: "32",
      hsi: "1",
      hk: "1",
      bsu: "1",
      kia: "0",
      blt: "1",
      bju: "1",
      bsb: "0",
      bad: "1",
      kik: "1",
      kki: "1",
      blu: "1",
      ikp: "1",
      bk: "1",
      bbu: "1",
    },
  ],
  "Kode lokasi": [
    {
      key: "0",
      kode_produk: "Edward King 0",
      kode_parent: "32",
      description: "32",
      hsi: "1",
      hk: "1",
      bsu: "1",
      kia: "0",
      blt: "1",
      bju: "1",
      bsb: "0",
      band: "1",
      kik: "1",
      kki: "1",
      blu: "1",
      ikp: "1",
      bk: "1",
      bbu: "1",
    },
  ],
  "Kode departemen": [
    {
      key: "0",
      kode_dept: "Edward King 0",
      description: "32",
    },
  ],
};
