const COL_WIDTH = 110;

export function getColumns() {
  return [
    {
      columnId: "code",
      width: 150,
      type: "text",
      nonEditabled: true,
    },
    {
      columnId: "description",
      width: 250,
      type: "text",
      nonEditabled: true,
    },

    {
      columnId: "jan",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "feb",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "mar",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "apr",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "mei",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "jun",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "jul",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "agu",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "sep",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "okt",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "nov",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "des",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "total_1",
      width: COL_WIDTH,
      type: "number",
    },

    {
      columnId: "jan_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "feb_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "mar_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "apr_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "mei_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "jun_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "jul_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "agu_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "sep_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "okt_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "nov_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "des_p",
      width: COL_WIDTH,
      type: "number",
      format: true,
      nonEditabled: true,
    },
    {
      columnId: "total_2",
      width: COL_WIDTH,
      type: "number",
    },
  ];
}
