export function getColumns() {
  return [
    { columnId: "grade", width: 150 },
    { columnId: "sub_grade", width: 150 },
    { columnId: "rate", width: 150 },
    { columnId: "sep", width: 150 },
    { columnId: "okt", width: 150 },
    { columnId: "nov", width: 150 },
    { columnId: "des", width: 150 },
    { columnId: "total", width: 150 },
    { columnId: "rate_p", width: 150 },
    { columnId: "jan_p", width: 150 },
    { columnId: "feb_p", width: 150 },
    { columnId: "mar_p", width: 150 },
    { columnId: "apr_p", width: 150 },
    { columnId: "mei_p", width: 150 },
    { columnId: "jun_p", width: 150 },
    { columnId: "jul_p", width: 150 },
    { columnId: "agu_p", width: 150 },
    { columnId: "sep_p", width: 150 },
    { columnId: "okt_p", width: 150 },
    { columnId: "nov_p", width: 150 },
    { columnId: "des_p", width: 150 },
    { columnId: "total_p", width: 150 },
  ];
}
