export const dataDummy = {
  list: [
    {
      title: "Stok Awal",
      data: [
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
      ],
    },
    {
      title: "Asumsi unit beli",
      data: [
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
      ],
    },
    {
      title: "Harga beli per unit",
      data: [
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
      ],
    },
    {
      title: "Stok akhir",
      data: [
        {
          description: "Vehicles",
          jan_actual: 0,
          feb_actual: 0,
          mar_actual: 0,
          apr_actual: 0,
          mei_actual: 0,
          jun_actual: 0,
          jul_actual: 0,
          agu_actual: 0,
          sep_actual: 0,
          nov_forecast: 0,
          des_forecast: 0,
        },
      ],
    },
  ],
};
