const COL_WIDTH = 110;

export const type1 = [
  {
    columnId: "project_code",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "project_description",
    width: 200,
    type: "text",
  },
  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const type2 = [
  {
    columnId: "project_code",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "description",
    width: 200,
    type: "text",
    nonEditabled: true,
  },

  { columnId: "jan", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const type3 = [
  {
    columnId: "project_code",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "project_description",
    width: 200,
    type: "text",
  },
  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", nonEditabled: true },
];

export const type4 = [
  {
    columnId: "project_code",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "project_description",
    width: 200,
    type: "text",
  },

  { columnId: "jan_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jan", width: COL_WIDTH, type: "percent" },
  { columnId: "feb_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb", width: COL_WIDTH, type: "percent" },
  { columnId: "mar_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar", width: COL_WIDTH, type: "percent" },
  { columnId: "apr_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr", width: COL_WIDTH, type: "percent" },
  { columnId: "mei_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei", width: COL_WIDTH, type: "percent" },
  { columnId: "jun_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun", width: COL_WIDTH, type: "percent" },
  { columnId: "jul_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul", width: COL_WIDTH, type: "percent" },
  { columnId: "agu_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu", width: COL_WIDTH, type: "percent" },
  { columnId: "sep_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep", width: COL_WIDTH, type: "percent" },
  { columnId: "okt_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt", width: COL_WIDTH, type: "percent" },
  { columnId: "nov_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov", width: COL_WIDTH, type: "percent" },
  { columnId: "des_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des", width: COL_WIDTH, type: "percent" },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jan_p", width: COL_WIDTH, type: "percent" },
  { columnId: "feb_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "percent" },
  { columnId: "mar_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "percent" },
  { columnId: "apr_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "percent" },
  { columnId: "mei_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "percent" },
  { columnId: "jun_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "percent" },
  { columnId: "jul_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "percent" },
  { columnId: "agu_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "percent" },
  { columnId: "sep_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "percent" },
  { columnId: "okt_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "percent" },
  { columnId: "nov_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "percent" },
  { columnId: "des_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des_p", width: COL_WIDTH, type: "percent" },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const type5 = [
  {
    columnId: "code_account",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "description",
    width: 200,
    type: "text",
  },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jan", width: COL_WIDTH, type: "percent" },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb", width: COL_WIDTH, type: "percent" },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar", width: COL_WIDTH, type: "percent" },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr", width: COL_WIDTH, type: "percent" },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei", width: COL_WIDTH, type: "percent" },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun", width: COL_WIDTH, type: "percent" },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul", width: COL_WIDTH, type: "percent" },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu", width: COL_WIDTH, type: "percent" },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep", width: COL_WIDTH, type: "percent" },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt", width: COL_WIDTH, type: "percent" },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov", width: COL_WIDTH, type: "percent" },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des", width: COL_WIDTH, type: "percent" },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jan_p", width: COL_WIDTH, type: "percent" },
  { columnId: "feb_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "percent" },
  { columnId: "mar_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "percent" },
  { columnId: "apr_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "percent" },
  { columnId: "mei_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "percent" },
  { columnId: "jun_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "percent" },
  { columnId: "jul_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "percent" },
  { columnId: "agu_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "percent" },
  { columnId: "sep_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "percent" },
  { columnId: "okt_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "percent" },
  { columnId: "nov_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "percent" },
  { columnId: "des_p_sd", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des_p", width: COL_WIDTH, type: "percent" },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const type6 = [
  {
    columnId: "code_account",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "description",
    width: 200,
    type: "text",
  },

  { columnId: "jan", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const type7 = [
  {
    columnId: "project_code",
    width: 200,
    type: "text",
    nonEditabled: true,
  },
  {
    columnId: "project_description",
    width: 200,
    type: "text",
    nonEditabled: true,
  },

  { columnId: "jan", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "total_1", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "jan_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "feb_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mar_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "apr_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "mei_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jun_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "jul_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "agu_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "sep_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "okt_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "nov_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
  { columnId: "des_p", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },

  { columnId: "total_2", width: COL_WIDTH, type: "number", format: true, nonEditabled: true },
];

export const getColumns = {
  "Stok Awal": type1,
  "Asumsi unit beli": type1,
  "Harga beli per unit": type3,
  "Stok akhir": type2,
  "Asumsi unit jual": type1,
  "Harga jual per unit": type3,
  Penjualan: type7,
  "Potongan penjualan": type4,
  "Pendapatan Operasional Lainnya": type6,
  "HPP Variable": type5,
  "HPP Lainnya": type6,
};
