export function getColumns() {
  return [
    { columnId: "grade", width: 150 },
    { columnId: "sub_grade", width: 150 },
    { columnId: "vacant", width: 150 },
    { columnId: "assessment", width: 150 },
    { columnId: "psychotest", width: 150 },
    { columnId: "mcu", width: 150 },
    { columnId: "welcome_pack", width: 150 },
    { columnId: "recruitment_total", width: 150 },
    { columnId: "year", width: 150 },
    { columnId: "assess_sep", width: 150 },
    { columnId: "assess_okt", width: 150 },
    { columnId: "assess_nov", width: 150 },
    { columnId: "assess_des", width: 150 },
    { columnId: "recruit_sep", width: 150 },
    { columnId: "recruit_okt", width: 150 },
    { columnId: "recruit_nov", width: 150 },
    { columnId: "recruit_des", width: 150 },
    { columnId: "assess_jan_p", width: 150 },
    { columnId: "assess_feb_p", width: 150 },
    { columnId: "assess_mar_p", width: 150 },
    { columnId: "assess_apr_p", width: 150 },
    { columnId: "assess_mei_p", width: 150 },
    { columnId: "assess_jun_p", width: 150 },
    { columnId: "assess_jul_p", width: 150 },
    { columnId: "assess_agu_p", width: 150 },
    { columnId: "assess_sep_p", width: 150 },
    { columnId: "assess_okt_p", width: 150 },
    { columnId: "assess_nov_p", width: 150 },
    { columnId: "assess_des_p", width: 150 },
    { columnId: "recruit_jan_p", width: 150 },
    { columnId: "recruit_feb_p", width: 150 },
    { columnId: "recruit_mar_p", width: 150 },
    { columnId: "recruit_apr_p", width: 150 },
    { columnId: "recruit_mei_p", width: 150 },
    { columnId: "recruit_jun_p", width: 150 },
    { columnId: "recruit_jul_p", width: 150 },
    { columnId: "recruit_agu_p", width: 150 },
    { columnId: "recruit_sep_p", width: 150 },
    { columnId: "recruit_okt_p", width: 150 },
    { columnId: "recruit_nov_p", width: 150 },
    { columnId: "recruit_des_p", width: 150 },
  ];
}
